<script lang="ts">
    let year = new Date().getFullYear();

    let scanURL: string = "";
    let loading: boolean = false;
    let requested: boolean = false;
    let error: string | null = null;
    let result: any = null;
    let showExportMenu: boolean = false;

    async function handleSubmit() {
        loading = true;
        requested = false;
        error = null;
        result = null;

        try {
            let response = await fetch('/api/extract', {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify({ url: scanURL })
            });
            let data = await response.json();

            if (!response.ok) {
                loading = false;
                requested = false;
                error = data.error || 'An error occurred';
                return;
            }

            loading = false;
            requested = true;
            error = null;
            result = data;
        } catch (err: any) {
            loading = false;
            requested = false;
            error = err.message || 'An error occurred';
        }
    }

    function exportJSON() {
        if (!result) return;
        const dataStr = JSON.stringify(result, null, 2);
        const dataBlob = new Blob([dataStr], { type: 'application/json' });
        const url = URL.createObjectURL(dataBlob);
        const link = document.createElement('a');
        link.href = url;
        const domain = result.url ? new URL(result.url).hostname.replace('www.', '') : 'design-tokens';
        link.download = `${domain}-design-tokens.json`;
        link.click();
        URL.revokeObjectURL(url);
    }

    function exportCSS() {
        if (!result) return;
        const domain = result.url ? new URL(result.url).hostname.replace('www.', '') : 'design-tokens';

        let css = `/**\n * Design Tokens - Extracted from ${result.url || 'website'}\n * Generated by DesignTree\n`;

        // Add detected frameworks/libraries as comments
        if (result.frameworks?.length > 0) {
            css += ` *\n * Detected Frameworks: ${result.frameworks.map((f: any) => f.name).join(', ')}\n`;
        }

        // Add detected icon systems as comments
        if (result.iconSystem?.length > 0) {
            css += ` * Icon Systems: ${result.iconSystem.map((i: any) => i.name).join(', ')}\n`;
        }

        css += ` */\n\n:root {\n`;

        // Colors
        if (result.colors?.palette) {
            css += '  /* Colors */\n';
            result.colors.palette.slice(0, 20).forEach((color: any, i: number) => {
                css += `  --color-${i + 1}: ${color.normalized};\n`;
            });
        }

        // Semantic colors
        if (result.colors?.semantic) {
            css += '\n  /* Semantic Colors */\n';
            Object.entries(result.colors.semantic).forEach(([name, value]: [string, any]) => {
                if (value) css += `  --color-${name}: ${value};\n`;
            });
        }

        // Typography
        if (result.typography?.styles) {
            css += '\n  /* Typography */\n';
            const families = [...new Set(result.typography.styles.map((s: any) => s.family))];
            families.forEach((family: any, i: number) => {
                css += `  --font-family-${i + 1}: "${family}";\n`;
            });
            // Font sizes
            const sizes = [...new Set(result.typography.styles.map((s: any) => s.size))].slice(0, 8);
            sizes.forEach((size: any, i: number) => {
                css += `  --font-size-${i + 1}: ${size};\n`;
            });
        }

        // Spacing
        if (result.spacing?.commonValues) {
            css += '\n  /* Spacing */\n';
            result.spacing.commonValues.slice(0, 10).forEach((sp: any, i: number) => {
                css += `  --spacing-${i + 1}: ${sp.px};\n`;
            });
        }

        // Border Radius
        if (result.borderRadius?.values) {
            css += '\n  /* Border Radius */\n';
            result.borderRadius.values.slice(0, 6).forEach((r: any, i: number) => {
                css += `  --radius-${i + 1}: ${r.value};\n`;
            });
        }

        // Shadows
        if (result.shadows?.length > 0) {
            css += '\n  /* Shadows */\n';
            result.shadows.slice(0, 4).forEach((s: any, i: number) => {
                css += `  --shadow-${i + 1}: ${s.shadow};\n`;
            });
        }

        // Borders
        if (result.borders?.length > 0) {
            css += '\n  /* Borders */\n';
            result.borders.slice(0, 4).forEach((b: any, i: number) => {
                css += `  --border-${i + 1}: ${b.width} ${b.style} ${b.color};\n`;
            });
        }

        // Breakpoints
        if (result.breakpoints?.length > 0) {
            css += '\n  /* Breakpoints */\n';
            result.breakpoints.forEach((bp: any, i: number) => {
                css += `  --breakpoint-${i + 1}: ${bp.px};\n`;
            });
        }

        css += '}\n';

        // Add CSS variables from the site
        if (result.colors?.cssVariables && Object.keys(result.colors.cssVariables).length > 0) {
            css += '\n/* Original CSS Variables from site */\n/*\n';
            Object.entries(result.colors.cssVariables).slice(0, 30).forEach(([name, value]: [string, any]) => {
                css += `  ${name}: ${value};\n`;
            });
            css += '*/\n';
        }

        const dataBlob = new Blob([css], { type: 'text/css' });
        const url = URL.createObjectURL(dataBlob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${domain}-tokens.css`;
        link.click();
        URL.revokeObjectURL(url);
    }

    function exportTailwind() {
        if (!result) return;
        const domain = result.url ? new URL(result.url).hostname.replace('www.', '').replace(/\./g, '-') : 'design';

        // Build colors object
        const colors: Record<string, string> = {};
        if (result.colors?.palette) {
            result.colors.palette.slice(0, 20).forEach((color: any, i: number) => {
                colors[`brand-${i + 1}`] = color.normalized;
            });
        }
        // Add semantic colors
        if (result.colors?.semantic) {
            Object.entries(result.colors.semantic).forEach(([name, value]: [string, any]) => {
                if (value) colors[name] = value;
            });
        }

        // Build font families
        const fontFamily: Record<string, string[]> = {};
        if (result.typography?.styles) {
            const families = [...new Set(result.typography.styles.map((s: any) => s.family))] as string[];
            if (families.length > 0) {
                fontFamily.sans = [families[0], 'system-ui', 'sans-serif'];
                if (families.length > 1) {
                    fontFamily.heading = [families[1], 'system-ui', 'sans-serif'];
                }
            }
        }

        // Build font sizes
        const fontSize: Record<string, string> = {};
        if (result.typography?.styles) {
            const sizes = [...new Set(result.typography.styles.map((s: any) => s.size))] as string[];
            sizes.slice(0, 8).forEach((size: string, i: number) => {
                fontSize[`custom-${i + 1}`] = size;
            });
        }

        // Build spacing
        const spacing: Record<string, string> = {};
        if (result.spacing?.commonValues) {
            result.spacing.commonValues.slice(0, 10).forEach((sp: any) => {
                const num = parseInt(sp.px);
                if (num > 0) {
                    spacing[num.toString()] = sp.px;
                }
            });
        }

        // Build border radius
        const borderRadius: Record<string, string> = {};
        if (result.borderRadius?.values) {
            result.borderRadius.values.slice(0, 6).forEach((r: any, i: number) => {
                borderRadius[`custom-${i + 1}`] = r.value;
            });
        }

        // Build box shadows
        const boxShadow: Record<string, string> = {};
        if (result.shadows?.length > 0) {
            result.shadows.slice(0, 4).forEach((s: any, i: number) => {
                boxShadow[`custom-${i + 1}`] = s.shadow;
            });
        }

        // Build breakpoints
        const screens: Record<string, string> = {};
        if (result.breakpoints) {
            result.breakpoints.forEach((bp: any) => {
                const num = parseInt(bp.px);
                if (num >= 320 && num <= 1920) {
                    screens[`${num}`] = bp.px;
                }
            });
        }

        // Build header comments
        let headerComments = `// Tailwind CSS Config - Extracted from ${result.url || 'website'}\n// Generated by DesignTree\n`;

        if (result.frameworks?.length > 0) {
            headerComments += `//\n// Detected Frameworks: ${result.frameworks.map((f: any) => f.name).join(', ')}\n`;
        }
        if (result.iconSystem?.length > 0) {
            headerComments += `// Icon Systems: ${result.iconSystem.map((i: any) => `${i.name} (${i.type})`).join(', ')}\n`;
        }
        if (result.typography?.sources) {
            const fontSources = [];
            if (result.typography.sources.googleFonts?.length > 0) fontSources.push(`Google Fonts: ${result.typography.sources.googleFonts.join(', ')}`);
            if (result.typography.sources.bunnyFonts?.length > 0) fontSources.push(`Bunny Fonts: ${result.typography.sources.bunnyFonts.join(', ')}`);
            if (result.typography.sources.adobeFonts) fontSources.push('Adobe Fonts');
            if (fontSources.length > 0) {
                headerComments += `// Font Sources: ${fontSources.join('; ')}\n`;
            }
        }

        const config = `${headerComments}
/** @type {import('tailwindcss').Config} */
export default {
  theme: {
    extend: {
      colors: ${JSON.stringify(colors, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
      fontFamily: ${JSON.stringify(fontFamily, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
      fontSize: ${JSON.stringify(fontSize, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
      spacing: ${JSON.stringify(spacing, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
      borderRadius: ${JSON.stringify(borderRadius, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
      boxShadow: ${JSON.stringify(boxShadow, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
      screens: ${JSON.stringify(screens, null, 8).replace(/"/g, "'").split('\n').map((l, i) => i === 0 ? l : '      ' + l).join('\n')},
    },
  },
  plugins: [],
}
`;
        const dataBlob = new Blob([config], { type: 'text/javascript' });
        const url = URL.createObjectURL(dataBlob);
        const link = document.createElement('a');
        link.href = url;
        link.download = `${domain}-tailwind.config.js`;
        link.click();
        URL.revokeObjectURL(url);
    }

    // Check if tech stack has any matches
    function hasTechStack(techStack: any): boolean {
        if (!techStack) return false;
        return Object.keys(techStack).some(key => techStack[key]?.length > 0);
    }
</script>

<svelte:head>
    <style>
        /* Hide scrollbars but keep scrolling */
        ::-webkit-scrollbar {
            display: none;
        }
        * {
            -ms-overflow-style: none;
            scrollbar-width: none;
        }
    </style>
</svelte:head>

<section class="py-4 py-xl-5">
    <div class="container" style="max-width: 600px;">
        <div class="text-center p-4 p-lg-5">
            <h1 class="display-4 text-start" style="font-family: Lora, serif;font-weight: 700;letter-spacing: -1px;margin-bottom: 16px;display: flex;align-items: center;">
                <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="#16a34a" fill="none" stroke-linecap="round" stroke-linejoin="round" style="height: 1em;width: 1em;margin-right: 6px;flex-shrink: 0;">
                    <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                    <!-- Trunk (drawn first, behind tree) -->
                    <path d="M14 17v3a1 1 0 0 1 -1 1h-2a1 1 0 0 1 -1 -1v-3" stroke="#8B4513" fill="#8B4513"></path>
                    <!-- Tree (drawn second, in front) -->
                    <path d="M12 3l4 4l-2 1l4 4l-3 1l4 4h-14l4 -4l-3 -1l4 -4l-2 -1z" fill="#16a34a"></path>
                </svg>
                DesignTree
            </h1>
            <p class="text-start" style="color: rgb(135,135,135);">Extract complete design systems and tech stack from any website. Get colors, typography, spacing, components, and technologies.</p>

            <form on:submit|preventDefault={handleSubmit} style="margin-bottom: 32px;margin-top: 48px;" method="get">
                <div class="input-group" style="margin-bottom: -16px;">
                    <input class="form-control" type="url" bind:value={scanURL} style="padding: 8px 16px;border-radius: 6px;background: rgba(255,255,255,0);border-top-right-radius: 0px;border-bottom-right-radius: 0px;font-weight: 500;outline: 0px !important;box-shadow: none !important;border: 2px solid #c5c5c5 ;border-right-style: none;" placeholder="https://example.com" name="url" required disabled={loading}>
                    <button class="btn btn-primary float-end" type="submit" style="border-radius: 6px;background: rgba(255,255,255,0);font-weight: 600;border-top-left-radius: 0px;border-bottom-left-radius: 0px;margin-left: -2px;padding: 8px 16px;color: rgb(33,37,41);outline: 0px !important;box-shadow: none !important;border: 2px solid #c5c5c5 ;border-left-style: none;" disabled={loading}>
                        <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-scan" style="font-size: 18px;margin-bottom: 3px;margin-right: 5px;">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M4 7v-1a2 2 0 0 1 2 -2h2"></path>
                            <path d="M4 17v1a2 2 0 0 0 2 2h2"></path>
                            <path d="M16 4h2a2 2 0 0 1 2 2v1"></path>
                            <path d="M16 20h2a2 2 0 0 0 2 -2v-1"></path>
                            <path d="M5 12l14 0"></path>
                        </svg>
                        Extract
                    </button>
                </div>
            </form>

            <p class="text-start" style="font-size: 14px;margin-bottom: 32px;">
                <a href="https://linktr.ee/solomonlijo" style="color: inherit;text-decoration: underline;text-decoration-color: #c5c5c5;" target="_blank">
                    Solomon Shalom Lijo
                    <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" class="icon icon-tabler icon-tabler-arrow-up-right" style="margin-top: -2px;margin-left: 2px;">
                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                        <path d="M17 7l-10 10"></path>
                        <path d="M8 7l9 0l0 9"></path>
                    </svg>
                </a>
            </p>

            {#if loading}
                <div id="loading" style="margin-top:64px;margin-bottom: 64px;">
                    <p class="text-center" style="font-weight: 500;"><span class="spinner-border spinner-border-sm" role="status" style="margin-right: 10px;width: 20px;height: 20px;margin-bottom: -3px;color: rgb(33,37,41);font-size: 12px;"></span>Extracting design system & tech stack (15-30s)...</p>
                </div>
            {/if}

            {#if requested && !loading && !result}
                <div style="margin-top:64px;margin-bottom: 64px;">
                    <p class="text-center" style="font-weight: 500;">
                        <svg class="icon icon-tabler icon-tabler-alert-circle" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" style="color: rgb(214,70,9);font-size: 22px;margin-right: 10px;margin-bottom: 3px;">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M3 12a9 9 0 1 0 18 0a9 9 0 0 0 -18 0"></path>
                            <path d="M12 8v4"></path>
                            <path d="M12 16h.01"></path>
                        </svg>
                        No data found
                    </p>
                </div>
            {/if}

            {#if error != null}
                <div style="margin-top:64px;margin-bottom: 64px;">
                    <p class="text-center" style="font-weight: 500;margin-bottom: 5px;">
                        <svg class="icon icon-tabler icon-tabler-alert-triangle" xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" style="color: rgb(204,45,35);font-size: 22px;margin-right: 10px;margin-bottom: 3px;">
                            <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                            <path d="M12 9v2m0 4v.01"></path>
                            <path d="M5 19h14a2 2 0 0 0 1.84 -2.75l-7.1 -12.25a2 2 0 0 0 -3.5 0l-7.1 12.25a2 2 0 0 0 1.75 2.75"></path>
                        </svg>
                        An error occurred while extracting
                    </p>
                    <p class="text-center" style="font-weight: 500;"><code style="color: rgb(204,45,35);padding: 5px 10px;background: rgba(204,45,35,0.1);border-radius: 5px;">{ error }</code></p>
                </div>
            {/if}

            {#if !loading && error == null && result}
                <div class="text-start" style="margin-top: 64px;margin-bottom: 64px;">

                    <!-- Export dropdown -->
                    <div style="margin-bottom: 32px;position: relative;display: inline-block;">
                        <button
                            on:click={() => showExportMenu = !showExportMenu}
                            style="padding: 8px 16px;border-radius: 6px;background: rgb(33,37,41);color: white;border: none;font-weight: 500;font-size: 13px;display: flex;align-items: center;gap: 8px;"
                        >
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M14 3v4a1 1 0 0 0 1 1h4"></path>
                                <path d="M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z"></path>
                                <path d="M12 17v-6"></path>
                                <path d="M9.5 14.5l2.5 2.5l2.5 -2.5"></path>
                            </svg>
                            Export
                            <svg xmlns="http://www.w3.org/2000/svg" width="1em" height="1em" viewBox="0 0 24 24" stroke-width="2" stroke="currentColor" fill="none" stroke-linecap="round" stroke-linejoin="round" style="margin-left: 2px;transition: transform 0.2s;transform: {showExportMenu ? 'rotate(180deg)' : 'rotate(0deg)'};">
                                <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                <path d="M6 9l6 6l6 -6"></path>
                            </svg>
                        </button>
                        {#if showExportMenu}
                            <div style="position: absolute;top: 100%;left: 0;margin-top: 6px;background: rgb(255,255,255);border: 1px solid rgb(206,207,208);border-radius: 8px;box-shadow: 0 4px 16px rgba(0,0,0,0.15);min-width: 160px;z-index: 100;overflow: hidden;">
                                <button
                                    on:click={() => { exportJSON(); showExportMenu = false; }}
                                    style="width: 100%;padding: 10px 14px;border: none;background: rgb(255,255,255);font-weight: 500;font-size: 13px;text-align: left;cursor: pointer;display: flex;align-items: center;gap: 10px;transition: background 0.15s;color: rgb(33,37,41);"
                                    on:mouseenter={(e) => e.currentTarget.style.background = 'rgb(243,244,246)'}
                                    on:mouseleave={(e) => e.currentTarget.style.background = 'rgb(255,255,255)'}
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="rgb(100,100,100)" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M14 3v4a1 1 0 0 0 1 1h4"></path>
                                        <path d="M17 21h-10a2 2 0 0 1 -2 -2v-14a2 2 0 0 1 2 -2h7l5 5v11a2 2 0 0 1 -2 2z"></path>
                                        <path d="M12 11v6"></path>
                                        <path d="M9.5 13.5l2.5 -2.5l2.5 2.5"></path>
                                    </svg>
                                    JSON
                                </button>
                                <button
                                    on:click={() => { exportCSS(); showExportMenu = false; }}
                                    style="width: 100%;padding: 10px 14px;border: none;background: rgb(255,255,255);font-weight: 500;font-size: 13px;text-align: left;cursor: pointer;display: flex;align-items: center;gap: 10px;transition: background 0.15s;border-top: 1px solid rgb(229,231,235);color: rgb(33,37,41);"
                                    on:mouseenter={(e) => e.currentTarget.style.background = 'rgb(243,244,246)'}
                                    on:mouseleave={(e) => e.currentTarget.style.background = 'rgb(255,255,255)'}
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="rgb(100,100,100)" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M20 4l-2 14.5l-6 2l-6 -2l-2 -14.5z"></path>
                                        <path d="M8.5 8h7l-4.5 6h4l-.5 3.5l-2.5 .75l-2.5 -.75l-.1 -.5"></path>
                                    </svg>
                                    CSS Variables
                                </button>
                                <button
                                    on:click={() => { exportTailwind(); showExportMenu = false; }}
                                    style="width: 100%;padding: 10px 14px;border: none;background: rgb(255,255,255);font-weight: 500;font-size: 13px;text-align: left;cursor: pointer;display: flex;align-items: center;gap: 10px;transition: background 0.15s;border-top: 1px solid rgb(229,231,235);color: rgb(33,37,41);"
                                    on:mouseenter={(e) => e.currentTarget.style.background = 'rgb(243,244,246)'}
                                    on:mouseleave={(e) => e.currentTarget.style.background = 'rgb(255,255,255)'}
                                >
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" viewBox="0 0 24 24" stroke-width="2" stroke="rgb(56,189,248)" fill="none" stroke-linecap="round" stroke-linejoin="round">
                                        <path stroke="none" d="M0 0h24v24H0z" fill="none"></path>
                                        <path d="M11.667 6c-2.49 0 -3.48 1.236 -3.667 3.667c.733 -1.222 1.59 -1.68 2.567 -1.375c.558 .174 .957 .576 1.398 1.022c.718 .725 1.549 1.564 3.367 1.564c2.49 0 3.48 -1.236 3.667 -3.667c-.733 1.222 -1.59 1.68 -2.567 1.375c-.558 -.174 -.957 -.576 -1.398 -1.022c-.718 -.725 -1.549 -1.564 -3.367 -1.564z"></path>
                                        <path d="M6.667 12c-2.49 0 -3.48 1.236 -3.667 3.667c.733 -1.222 1.59 -1.68 2.567 -1.375c.558 .174 .957 .576 1.398 1.022c.718 .725 1.549 1.564 3.367 1.564c2.49 0 3.48 -1.236 3.667 -3.667c-.733 1.222 -1.59 1.68 -2.567 1.375c-.558 -.174 -.957 -.576 -1.398 -1.022c-.718 -.725 -1.549 -1.564 -3.367 -1.564z"></path>
                                    </svg>
                                    Tailwind Config
                                </button>
                            </div>
                        {/if}
                    </div>

                    <div class="row row-cols-2">
                        <!-- Tech Stack (from ingredients) -->
                        {#if hasTechStack(result.techStack)}
                            {#each Object.keys(result.techCategories || {}) as category}
                                {#if result.techStack[category]?.length > 0}
                                    <div class="col-12 col-sm-6">
                                        <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                            <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">{result.techCategories[category]}</h2>
                                            <ul class="list-unstyled">
                                                {#each result.techStack[category] as tech}
                                                    <li style="margin-bottom: 4px;font-weight: 500;">
                                                        {tech.name}
                                                    </li>
                                                {/each}
                                            </ul>
                                        </div>
                                    </div>
                                {/if}
                            {/each}
                        {/if}

                        <!-- Colors -->
                        {#if result.colors?.palette?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Colors</h2>
                                    <ul class="list-unstyled">
                                        {#each result.colors.palette.slice(0, 12) as color}
                                            <li style="margin-bottom: 8px;font-weight: 500;display: flex;align-items: center;">
                                                <span style="width: 24px;height: 24px;border-radius: 4px;margin-right: 10px;border: 1px solid rgb(206,207,208);background-color: {color.normalized};display: inline-block;flex-shrink: 0;"></span>
                                                <code style="font-size: 13px;background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;">{color.normalized}</code>
                                                {#if color.confidence === 'high'}
                                                    <span style="margin-left: 8px;font-size: 10px;background: rgba(34,197,94,0.1);color: rgb(22,163,74);padding: 2px 6px;border-radius: 4px;">high</span>
                                                {/if}
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Typography -->
                        {#if result.typography?.styles?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Typography</h2>
                                    <ul class="list-unstyled">
                                        {#each [...new Set(result.typography.styles.map((s) => s.family))].slice(0, 6) as family}
                                            <li style="margin-bottom: 8px;font-weight: 500;">
                                                <span style="font-family: {family};">{family}</span>
                                            </li>
                                        {/each}
                                    </ul>
                                    <!-- Font Sources -->
                                    <div style="margin-top: 16px;padding-top: 12px;border-top: 1px solid rgba(33,37,41,0.1);">
                                        {#if result.typography.sources?.googleFonts?.length > 0}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(66,133,244);">Google Fonts:</span> {result.typography.sources.googleFonts.join(', ')}
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.bunnyFonts?.length > 0}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(255,153,0);">Bunny Fonts:</span> {result.typography.sources.bunnyFonts.join(', ')}
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.fontshare?.length > 0}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(147,51,234);">Fontshare:</span> {result.typography.sources.fontshare.join(', ')}
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.adobeFonts}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(255,0,0);">Adobe Fonts:</span> Typekit detected
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.selfHosted?.length > 0}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(34,197,94);">Self-hosted:</span> {result.typography.sources.selfHosted.map(f => f.name).join(', ')}
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.systemFonts?.length > 0}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(100,116,139);">System fonts:</span> {result.typography.sources.systemFonts.join(', ')}
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.variableFonts?.length > 0}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 4px;">
                                                <span style="font-weight: 600;color: rgb(236,72,153);">Variable fonts:</span> {result.typography.sources.variableFonts.join(', ')}
                                            </p>
                                        {/if}
                                        {#if result.typography.sources?.fontDisplay}
                                            <p style="font-size: 11px;color: rgb(135,135,135);margin-bottom: 0;">
                                                <span style="font-weight: 600;">font-display:</span> {result.typography.sources.fontDisplay}
                                            </p>
                                        {/if}
                                    </div>
                                </div>
                            </div>
                        {/if}

                        <!-- Icon Systems -->
                        {#if result.iconSystem?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Icon Systems</h2>
                                    <ul class="list-unstyled">
                                        {#each result.iconSystem as icon}
                                            <li style="margin-bottom: 10px;font-weight: 500;">
                                                <div style="display: flex;align-items: center;justify-content: space-between;flex-wrap: wrap;gap: 8px;">
                                                    <span style="display: flex;align-items: center;gap: 4px;">
                                                        {icon.name}
                                                        {#if icon.version && icon.version !== 'Unknown'}
                                                            <span style="font-size: 10px;color: rgb(135,135,135);">v{icon.version}</span>
                                                        {/if}
                                                    </span>
                                                    <span style="display: flex;align-items: center;gap: 6px;flex-shrink: 0;">
                                                        {#if icon.count}
                                                            <span style="font-size: 10px;background: rgba(33,37,41,0.05);color: rgb(100,100,100);padding: 3px 8px;border-radius: 4px;white-space: nowrap;">{icon.count}</span>
                                                        {/if}
                                                        <span style="font-size: 10px;background: {icon.type === 'icon-font' ? 'rgba(99,102,241,0.1)' : icon.type === 'svg' ? 'rgba(34,197,94,0.1)' : 'rgba(251,146,60,0.1)'};color: {icon.type === 'icon-font' ? 'rgb(79,70,229)' : icon.type === 'svg' ? 'rgb(22,163,74)' : 'rgb(234,88,12)'};padding: 3px 8px;border-radius: 4px;white-space: nowrap;">{icon.type}</span>
                                                    </span>
                                                </div>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Spacing -->
                        {#if result.spacing?.commonValues?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Spacing</h2>
                                    <p style="font-size: 12px;color: rgb(135,135,135);margin-bottom: 12px;">Scale: {result.spacing.scaleType}</p>
                                    <ul class="list-unstyled">
                                        {#each result.spacing.commonValues.slice(0, 8) as spacing}
                                            <li style="margin-bottom: 6px;font-weight: 500;display: flex;align-items: center;">
                                                <span style="width: {Math.min(spacing.numericValue, 60)}px;height: 8px;background: linear-gradient(90deg, rgb(33,37,41), rgb(100,100,100));border-radius: 2px;margin-right: 10px;"></span>
                                                <code style="font-size: 13px;background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;">{spacing.px}</code>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Border Radius -->
                        {#if result.borderRadius?.values?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Border Radius</h2>
                                    <ul class="list-unstyled">
                                        {#each result.borderRadius.values.slice(0, 6) as radius}
                                            <li style="margin-bottom: 8px;font-weight: 500;display: flex;align-items: center;">
                                                <span style="width: 24px;height: 24px;border: 2px solid rgb(33,37,41);border-radius: {radius.value};margin-right: 10px;display: inline-block;"></span>
                                                <code style="font-size: 13px;background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;">{radius.value}</code>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Borders -->
                        {#if result.borders?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Borders</h2>
                                    <ul class="list-unstyled">
                                        {#each result.borders.slice(0, 6) as border}
                                            <li style="margin-bottom: 10px;display: flex;align-items: center;gap: 10px;">
                                                <span style="width: 40px;height: 24px;border: {border.width} {border.style} {border.color};border-radius: 4px;display: inline-block;flex-shrink: 0;"></span>
                                                <div style="flex: 1;">
                                                    <code style="font-size: 11px;background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;">{border.width} {border.style}</code>
                                                    <span style="width: 12px;height: 12px;border-radius: 2px;background-color: {border.color};display: inline-block;margin-left: 6px;vertical-align: middle;border: 1px solid rgba(0,0,0,0.1);"></span>
                                                    {#if border.elements?.length > 0}
                                                        <span style="font-size: 10px;color: rgb(135,135,135);margin-left: 6px;">{border.elements.slice(0, 3).join(', ')}</span>
                                                    {/if}
                                                </div>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Shadows -->
                        {#if result.shadows?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Shadows</h2>
                                    <ul class="list-unstyled">
                                        {#each result.shadows.slice(0, 4) as shadow}
                                            <li style="margin-bottom: 12px;">
                                                <div style="width: 100%;height: 40px;background: white;border-radius: 6px;box-shadow: {shadow.shadow};margin-bottom: 6px;"></div>
                                                <code style="font-size: 10px;background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;word-break: break-all;">{shadow.shadow.substring(0, 50)}...</code>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Buttons -->
                        {#if result.components?.buttons?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Buttons</h2>
                                    <ul class="list-unstyled">
                                        {#each result.components.buttons.slice(0, 4) as button}
                                            <li style="margin-bottom: 12px;">
                                                <span style="
                                                    display: inline-block;
                                                    padding: 8px 16px;
                                                    background-color: {button.states?.default?.backgroundColor || 'transparent'};
                                                    color: {button.states?.default?.color || '#000'};
                                                    border: {button.states?.default?.border || 'none'};
                                                    border-radius: {button.states?.default?.borderRadius || '4px'};
                                                    font-weight: {button.fontWeight || '500'};
                                                    font-size: 13px;
                                                ">Button</span>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Inputs -->
                        {#if result.components?.inputs && Object.keys(result.components.inputs).length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Inputs</h2>
                                    <ul class="list-unstyled">
                                        {#each Object.entries(result.components.inputs).slice(0, 4) as [type, inputs]}
                                            {#if inputs.length > 0}
                                                {@const input = inputs[0]}
                                                <li style="margin-bottom: 12px;">
                                                    <div style="
                                                        padding: 8px 12px;
                                                        background-color: {input.states?.default?.backgroundColor || '#fff'};
                                                        color: {input.states?.default?.color || '#333'};
                                                        border: {input.states?.default?.border || '1px solid #ccc'};
                                                        border-radius: {input.states?.default?.borderRadius || '4px'};
                                                        font-size: 13px;
                                                        max-width: 200px;
                                                    ">
                                                        <span style="color: {input.states?.default?.placeholderColor || 'rgba(0,0,0,0.4)'};">placeholder</span>
                                                    </div>
                                                    <span style="font-size: 10px;color: rgb(135,135,135);margin-top: 4px;display: block;">{type}</span>
                                                </li>
                                            {/if}
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Links -->
                        {#if result.components?.links?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Links</h2>
                                    <ul class="list-unstyled">
                                        {#each result.components.links.slice(0, 4) as link}
                                            <li style="margin-bottom: 10px;">
                                                <span style="
                                                    color: {link.states?.default?.color || '#0066cc'};
                                                    text-decoration: {link.states?.default?.textDecoration || 'underline'};
                                                    font-weight: {link.fontWeight || 'normal'};
                                                    font-size: 14px;
                                                ">Link Text</span>
                                                <span style="font-size: 10px;background: rgba(33,37,41,0.05);color: rgb(100,100,100);padding: 2px 6px;border-radius: 4px;margin-left: 8px;">{link.context || 'inline'}</span>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Frameworks & Design Libraries (from dembrandt) -->
                        {#if result.frameworks?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Frameworks & Libraries</h2>
                                    <ul class="list-unstyled">
                                        {#each result.frameworks as framework}
                                            <li style="margin-bottom: 10px;font-weight: 500;">
                                                <div style="display: flex;align-items: center;justify-content: space-between;flex-wrap: wrap;gap: 6px;">
                                                    <span>{framework.name}</span>
                                                    <span style="font-size: 10px;background: {framework.confidence === 'high' ? 'rgba(34,197,94,0.1)' : 'rgba(251,146,60,0.1)'};color: {framework.confidence === 'high' ? 'rgb(22,163,74)' : 'rgb(234,88,12)'};padding: 3px 8px;border-radius: 4px;">{framework.confidence}</span>
                                                </div>
                                                {#if framework.evidence}
                                                    <div style="font-size: 11px;color: rgb(135,135,135);margin-top: 2px;">{framework.evidence}</div>
                                                {/if}
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Breakpoints -->
                        {#if result.breakpoints?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Breakpoints</h2>
                                    <ul class="list-unstyled" style="display: flex;flex-wrap: wrap;gap: 8px;">
                                        {#each result.breakpoints as bp}
                                            <li>
                                                <code style="font-size: 13px;background: rgba(33,37,41,0.05);padding: 4px 8px;border-radius: 4px;">{bp.px}</code>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Badges & Tags -->
                        {#if result.components?.badges?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Badges & Tags</h2>
                                    <ul class="list-unstyled" style="display: flex;flex-wrap: wrap;gap: 8px;">
                                        {#each result.components.badges.slice(0, 10) as badge}
                                            <li>
                                                <span style="
                                                    display: inline-block;
                                                    padding: {badge.styles?.padding || '4px 8px'};
                                                    background-color: {badge.styles?.backgroundColor || '#f3f4f6'};
                                                    color: {badge.styles?.color || '#374151'};
                                                    border: {badge.styles?.border || 'none'};
                                                    border-radius: {badge.styles?.borderRadius || '9999px'};
                                                    font-size: {badge.styles?.fontSize || '12px'};
                                                    font-weight: {badge.styles?.fontWeight || '500'};
                                                ">{badge.text || badge.type}</span>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Accessibility Score -->
                        {#if result.accessibility?.summary}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Accessibility</h2>
                                    <div style="margin-bottom: 16px;">
                                        <div style="display: flex;align-items: center;gap: 12px;margin-bottom: 12px;">
                                            <div style="
                                                width: 60px;
                                                height: 60px;
                                                border-radius: 50%;
                                                display: flex;
                                                align-items: center;
                                                justify-content: center;
                                                font-size: 20px;
                                                font-weight: bold;
                                                background: {result.accessibility.summary.score >= 80 ? 'rgba(34,197,94,0.1)' : result.accessibility.summary.score >= 50 ? 'rgba(251,146,60,0.1)' : 'rgba(239,68,68,0.1)'};
                                                color: {result.accessibility.summary.score >= 80 ? 'rgb(22,163,74)' : result.accessibility.summary.score >= 50 ? 'rgb(234,88,12)' : 'rgb(220,38,38)'};
                                            ">{result.accessibility.summary.score}</div>
                                            <div>
                                                <div style="font-weight: 600;margin-bottom: 2px;">{result.accessibility.summary.passesMinimumAA ? 'Passes WCAG AA' : 'Needs Improvement'}</div>
                                                <div style="font-size: 12px;color: rgb(135,135,135);">{result.accessibility.summary.errors} errors, {result.accessibility.summary.warnings} warnings</div>
                                            </div>
                                        </div>
                                    </div>
                                    {#if result.accessibility.issues?.length > 0}
                                        <ul class="list-unstyled" style="max-height: 150px;overflow-y: auto;">
                                            {#each result.accessibility.issues.slice(0, 5) as issue}
                                                <li style="margin-bottom: 8px;font-size: 12px;display: flex;align-items: flex-start;gap: 8px;">
                                                    <span style="
                                                        flex-shrink: 0;
                                                        width: 18px;
                                                        height: 18px;
                                                        border-radius: 50%;
                                                        display: flex;
                                                        align-items: center;
                                                        justify-content: center;
                                                        font-size: 10px;
                                                        background: {issue.severity === 'error' ? 'rgba(239,68,68,0.1)' : 'rgba(251,146,60,0.1)'};
                                                        color: {issue.severity === 'error' ? 'rgb(220,38,38)' : 'rgb(234,88,12)'};
                                                    ">{issue.severity === 'error' ? '!' : '?'}</span>
                                                    <span style="color: rgb(75,85,99);">{issue.message}</span>
                                                </li>
                                            {/each}
                                        </ul>
                                    {/if}
                                </div>
                            </div>
                        {/if}

                        <!-- Forms -->
                        {#if result.components?.forms?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Forms ({result.components.forms.length})</h2>
                                    <ul class="list-unstyled">
                                        {#each result.components.forms.slice(0, 3) as form, i}
                                            <li style="margin-bottom: 16px;padding: 12px;background: rgba(33,37,41,0.02);border-radius: 8px;">
                                                <div style="font-weight: 600;font-size: 13px;margin-bottom: 8px;">Form {i + 1}</div>
                                                <div style="font-size: 11px;color: rgb(135,135,135);display: flex;flex-wrap: wrap;gap: 8px;">
                                                    <span style="background: rgba(99,102,241,0.1);color: rgb(79,70,229);padding: 2px 6px;border-radius: 4px;">{form.fields?.length || 0} fields</span>
                                                    {#if form.fieldsets?.length > 0}
                                                        <span style="background: rgba(34,197,94,0.1);color: rgb(22,163,74);padding: 2px 6px;border-radius: 4px;">{form.fieldsets.length} fieldsets</span>
                                                    {/if}
                                                    {#if form.validationPatterns?.length > 0}
                                                        <span style="background: rgba(251,146,60,0.1);color: rgb(234,88,12);padding: 2px 6px;border-radius: 4px;">{form.validationPatterns.length} validations</span>
                                                    {/if}
                                                    <span style="background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;">{form.layout}</span>
                                                </div>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- Gradients -->
                        {#if result.colors?.gradients?.length > 0}
                            <div class="col-12 col-sm-6">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">Gradients</h2>
                                    <ul class="list-unstyled">
                                        {#each result.colors.gradients.slice(0, 6) as gradient}
                                            <li style="margin-bottom: 12px;">
                                                <div style="width: 100%;height: 32px;border-radius: 6px;background: {gradient.value};border: 1px solid rgb(206,207,208);margin-bottom: 6px;"></div>
                                                <span style="font-size: 10px;background: rgba(147,51,234,0.1);color: rgb(126,34,206);padding: 2px 6px;border-radius: 4px;">{gradient.type}</span>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}

                        <!-- CSS Variables -->
                        {#if result.colors?.cssVariables && Object.keys(result.colors.cssVariables).length > 0}
                            <div class="col-12">
                                <div style="border-width: 2px;border-top-style: solid;border-top-color: rgb(33,37,41);margin-bottom: 50px;">
                                    <h2 class="fs-5" style="font-weight: bold;margin-top: 6px;margin-bottom: 16px;font-family: Lora, serif;">CSS Variables ({Object.keys(result.colors.cssVariables).length})</h2>
                                    <ul class="list-unstyled" style="max-height: 300px;overflow-y: auto;display: grid;grid-template-columns: repeat(auto-fill, minmax(280px, 1fr));gap: 4px 16px;">
                                        {#each Object.entries(result.colors.cssVariables).slice(0, 50) as [name, value]}
                                            <li style="font-size: 11px;display: flex;align-items: center;padding: 4px 0;">
                                                <code style="background: rgba(33,37,41,0.05);padding: 2px 6px;border-radius: 4px;margin-right: 8px;max-width: 160px;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;" title="{name}">{name}</code>
                                                {#if value.startsWith('#') || value.startsWith('rgb') || value.startsWith('hsl')}
                                                    <span style="width: 14px;height: 14px;border-radius: 3px;background-color: {value};border: 1px solid rgb(206,207,208);margin-right: 6px;flex-shrink: 0;"></span>
                                                {/if}
                                                <span style="color: rgb(135,135,135);max-width: 100px;overflow: hidden;text-overflow: ellipsis;white-space: nowrap;" title="{value}">{value}</span>
                                            </li>
                                        {/each}
                                    </ul>
                                </div>
                            </div>
                        {/if}
                    </div>
                </div>
            {/if}

            <footer class="text-start" style="margin-top: 70px;padding-top: 24px;border-top: 2px solid rgb(197,197,197) ;">
                <p style="color: rgba(33,37,41,0.5);font-size: 12px;font-weight: 500;">
                    Copyright © { year } DesignTree
                </p>
                <p style="color: rgba(33,37,41,0.5);font-size: 12px;">
                    Powered by <a href="https://github.com/thevangelist/dembrandt" style="color: inherit;" target="_blank">dembrandt</a> and <a href="https://github.com/berrysauce/ingredients" style="color: inherit;" target="_blank">ingredients</a>.
                    No personal data is collected.
                </p>
            </footer>
        </div>
    </div>
</section>
